version: 2.1

parameters:
  kre-image-tag:
    type: string
    default: "9-latest"
  agent-download-link:
    type: string
    default: ""
  job-info:
    type: string
    default: ""
  agent-config:
    type: string
    default: ""
  server-url:
    type: string
    default: ""

orbs:
  slack: circleci/slack@4.12.6

slack_notify: &slack_notify
  slack/notify:
    event: fail
    template: basic_fail_1
setup_slack_mentions: &setup_slack_mentions
  run:
    name: setup $SLACK_PARAM_MENTIONS
    command: |
      echo "export SLACK_PARAM_MENTIONS='$(printenv "GH_USER_${CIRCLE_USERNAME//-/__DASH__}")'" >> "$BASH_ENV"

jobs:
  katalon-studio-run:
    docker:
      - image: katalonstudio/katalon:9-latest 
    
    steps:
      - *setup_slack_mentions
      - checkout
      - run:
          name: Regression Tests
          command: |
            katalonc.sh -apiKey="$KATALON_API_KEY" -browserType="Chrome" \
              -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Regression" \
              -projectPath="" --config -webui.autoUpdateDrivers=true
 #     - run:    
 #         name: UI Tests
 #         command: |
 #          katalonc.sh -apiKey="$KATALON_API_KEY" -browserType="Chrome" \
 #             -retry=0 -statusDelay=15 -testSuitePath="Test Suites/UI" \
#            -projectPath="./" --config -webui.autoUpdateDrivers=true
      - store_artifacts:
          path: Reports
      - store_test_results:
          path: Reports

workflows:
  build:
    jobs:
      - katalon-studio-run:
          context: org-global